name: CI Pipeline

on: [push, pull_request]

jobs:
  code_checker:
    name: code checker
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "/home/runner/work/torch_semantic_segmentation/torch_semantic_segmentation"
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
        # Use the same Python version as your project
          python-version: "3.12.9"
      - name: upgrade pip
        run:
          python -m pip install --upgrade pip
          
      - name: Install Poetry
        run: pip install poetry
        
      - name: Install dependencies
        run: | 
            poetry install  --no-interaction --no-root --all-groups
            # use cpu version of torch and torchvision
            poetry run pip install torch torchvision
        
      - name: Run pylint - checks for code quality issues, style violations, and some security concerns
        run: | 
            poetry run pylint . --exit-zero
            poetry run pylint . --errors-only
            
      - name: Run mypy - performs static type checking using type annotations
        run: |
            poetry run mypy -p src --config-file pyproject.toml --no-namespace-packages
            poetry run mypy -p tests --config-file pyproject.toml 
            
      - name: run tests
        run: |
          echo $PYTHONPATH
          poetry run pytest
      # - name: Run pylint on src
        # run: run pylint ./src --exit-zero 
      
      # - name: Run pylint on tests     
        # run: run pylint ./tests --exit-zero # --fail-on=error  
        # uses: github/super-linter@v4
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
